### PR TITLE
Add list initContainers images function

### PR DESCRIPTION
**Pull request by Luffy110**
Hi i added this function , Do you consider have this function ? if yes, can you merge this?

### CODE REVIEW

**Comment by Luffy110** [comment]
add this function propose. [issue 6](https://github.com/chenjiandongx/kubectl-images/issues/6)

**Comment by chenjiandongx** [comment]
Hi @Luffy110 , thanks for your contributions.

I have tested your PR and It works as expected :), 

image

But there is a suggestion that you can consider. After added `init containers`, dose them need something special mark like `(init)` to claim for users?

**Comment by Luffy110** [comment]
Hi you are right! i have added your proposal for more readability. Thanks!

**Comment by chenjiandongx** [comment]
Look good to me, I will release a new version later and update to krew-index.

**Pull request merged**
